Feature add sample batch job
opsnow-tools/valve-awsbatch pull request #3
Opened 2019-10-23 01:09 UTC by pakisto

배치 인프라를 구성하는 것과 배치 잡을 구성하는 것은 다른 라이프 사이클을 가집니다. 
따라서, 별도의 모듈로 개발될 수 있도록 디렉토리를 구분하여 템플릿을 제공합니다.

2019-10-23 02:54 UTC, gelius7 commented on examples/batch-job/job-sample-r.tf
> +  "image": "docker-registry-devops.coruscant.opsnow.com/sample-r",
주소가 노출됩니다.

2019-10-23 02:55 UTC, gelius7 commented on templates/batch-job/job-template.tf
> +  image_name = "docker-registry-devops.coruscant.opsnow.com/sample-r"
여기도 registry 주소가 노출됩니다.

2019-10-23 02:56 UTC, gelius7 requested changes
주소 노출되는 부분을 가리고 올리면 좋겠습니다.

2019-10-24 01:55 UTC, pakisto commented
향후 인증으로 커버하시죠.

2019-10-24 02:18 UTC, longlg88 approved these changes
확인했습니다.

2019-10-24 02:25 UTC, merged